const BASE_URL = 'http://16.171.126.47:5000/api/v1'; //dev
// const BASE_URL = 'http://localhost:5001/api/v1'; //local
// const BASE_URL = 'http://192.168.29.230:5001/api/v1'; //local
// var BASE_URL = 'http://43.204.45.2:5000/api/v1'; //QA
// var BASE_URL = 'http://43.204.45.2:5001/api/v1'; //PROD

export const LOGIN_URL = BASE_URL + '/login';
export const SIGN_UP_URL = BASE_URL + '/signup';
export const GET_DOCTOR_LIST_URL = BASE_URL + '/getdoctorlist';
export const GET_DOCTOR = BASE_URL + '/getdoctor';
export const ADD_DOCTOR_URL = BASE_URL + '/adddoctor';
export const LINK_DOCTOR_URL = BASE_URL + '/linkDoctor';
export const GET_CLINIC_LIST_URL = BASE_URL + '/getcliniclist';
export const ADD_AVAILABILITY_URL = BASE_URL + '/addavailability';
export const GET_AVAILABILITY_URL = BASE_URL + '/getavailability';
export const AVAILABILITY_URL = BASE_URL + '/availability';
export const GET_APPOINTMENTS_URL = BASE_URL + '/getAppointments';
export const ADDADDRESS_URL = BASE_URL + '/addaddress';
export const GET_ADDRESS_URL = BASE_URL + '/getaddress';
export const ADD_LEAVE_URL = BASE_URL + '/addLeave';
export const LEAVE = BASE_URL + '/leave';
export const UPDATE_DOCTOR = BASE_URL + '/updateDoctor';
export const GET_LEAVE_URL = BASE_URL + '/getLeaves';
export const UPDATE_SLOTS_STATUS_URL = BASE_URL + '/updateSlotsStatus';
export const updateClinicUrl = BASE_URL + '/updateClinic';
export const GET_BOOKING_SUMMARY_Url = BASE_URL + '/getBookingsSummary';
export const DOCUMENT = BASE_URL + '/document';
export const GET_SPECIALTY_URL = BASE_URL + '/getSpeciality';
export const REMOVE_DOCTOR_MAPPING_URL = BASE_URL + '/removeDoctorMapping';
export const GETLOCATION_URL = BASE_URL + '/getLocation';
