const BASE_URL = 'http://16.171.126.47:80/api/v1'; //dev
// const BASE_URL = 'http://13.233.253.68:5000/api/v1'; //prod

export const LOGIN_URL = BASE_URL + '/login';
export const signup_URL = BASE_URL + '/signup';
export const GETDOCTORLIST_URL = BASE_URL + '/getdoctorlist';
export const GET_DOCTOR = BASE_URL + '/getdoctor';
export const ADDDOCTOR_URL = BASE_URL + '/adddoctor';
export const LINK_DOCTOR_URL = BASE_URL + '/linkDoctor';
export const GETCLINICLIST_URL = BASE_URL + '/getcliniclist';
export const ADDAVAILABILITY_URL = BASE_URL + '/addavailability';
export const GETAVAILABILITY_URL = BASE_URL + '/getavailability';
export const GETAPPOINTMENTS_URL = BASE_URL + '/getAppointments';
export const ADDADDRESS_URL = BASE_URL + '/addaddress';
export const GETADDRESS_URL = BASE_URL + '/getaddress';
export const ADDLEAVE_URL = BASE_URL + '/addLeave';
export const UPDATE_DOCTOR = BASE_URL + '/updateDoctor';
export const GETLEAVE_URL = BASE_URL + '/getLeaves';
export const UPDATESLOTSSTATUS_URL = BASE_URL + '/updateSlotsStatus';
export const updateClinicUrl = BASE_URL + '/updateClinic';
